// Reads and rewrites the object/array literal blocks in src/data/*.js that
// the dev admin page (/__admin) edits. Each editable block is located by an
// anchor string, extracted with a bracket matcher that understands string
// literals and comments, evaluated to plain data for the UI, and — on save —
// regenerated by a pretty-printer that matches the repo's prettier style
// (single quotes, 2-space indent, trailing commas, wrapped long strings).
//
// Everything OUTSIDE the block (doc-comment headers, helper functions,
// exports) is untouched. Comments INSIDE a block are dropped on save; the
// data files' headers say so.
//
// Literal consts declared in the same file (HOME_TITLE in seo-config.js,
// LOREM_BODY in crowdfundingGames.js) are resolved when reading and
// re-substituted when writing, so the indirection survives a round trip.
//
// Blocks marked `optional` cover files that only exist in some repos —
// kato8-staging carries crowdfundingGames.js, prod doesn't (yet). They're
// simply absent from the admin when the file is missing.

import fs from 'node:fs'
import path from 'node:path'

export const BLOCKS = {
  games: { file: 'src/data/games.js', anchor: 'const rawGames = ' },
  staticRoutes: { file: 'src/data/seo-config.js', anchor: 'export const staticRoutes = ' },
  gameRoutes: { file: 'src/data/seo-config.js', anchor: 'export const gameRoutes = ' },
  discordEndpoints: { file: 'src/data/discordEndpoints.js', anchor: 'export const discordEndpoints = ' },
  playtestEndpoints: { file: 'src/data/playtestEndpoints.js', anchor: 'export const playtestEndpoints = ' },
  crowdfundingGames: { file: 'src/data/crowdfundingGames.js', anchor: 'export const crowdfundingGames = ', optional: true },
  // Content blocks that live inside components — the block editor works on
  // any file, as long as the anchored literal is pure data.
  socialLinks: { file: 'src/components/SocialIcons.jsx', anchor: 'export const socialLinks = ' },
  footerSocials: { file: 'src/components/Footer.jsx', anchor: 'const footerSocials = ' },
  aboutContent: { file: 'src/pages/AboutPage.jsx', anchor: 'const aboutContent = ' },
  heroContent: { file: 'src/components/Hero.jsx', anchor: 'const heroContent = ' },
}

// The variable each block's anchor declares — excluded from const
// resolution so a block never gets "substituted" by its own name.
const BLOCK_VARS = new Set(Object.values(BLOCKS).map(({ anchor }) => anchor.match(/const (\w+) =/)[1]))

export function blockAvailable(root, name) {
  const spec = BLOCKS[name]
  return !spec.optional || fs.existsSync(path.join(root, spec.file))
}

// Walk source from an opening bracket to its matching close, skipping
// strings ('', "", ``) and comments so braces inside them don't count.
function matchBracket(src, openIdx) {
  const open = src[openIdx]
  const close = { '[': ']', '{': '}' }[open]
  let depth = 0
  for (let i = openIdx; i < src.length; i++) {
    const c = src[i]
    if (c === "'" || c === '"' || c === '`') {
      for (i++; i < src.length && src[i] !== c; i++) if (src[i] === '\\') i++
    } else if (c === '/' && src[i + 1] === '/') {
      i = src.indexOf('\n', i)
      if (i === -1) break
    } else if (c === '/' && src[i + 1] === '*') {
      i = src.indexOf('*/', i) + 1
    } else if (c === open) depth++
    else if (c === close && --depth === 0) return i
  }
  throw new Error(`unbalanced ${open} at index ${openIdx}`)
}

function findBlock(src, anchor) {
  const at = src.indexOf(anchor)
  if (at === -1) throw new Error(`anchor not found: "${anchor}"`)
  const start = at + anchor.length
  if (!'[{'.includes(src[start])) throw new Error(`no literal after anchor "${anchor}"`)
  return { start, end: matchBracket(src, start) + 1 }
}

// Top-level `const NAME = <literal>` declarations (string, array, or object
// literals), for identifier resolution inside blocks and re-substitution on
// write. Evaluated in file order so a const may reference earlier ones.
// Non-literal consts (computed expressions) are skipped.
function fileConsts(src) {
  const consts = {}
  for (const m of src.matchAll(/^(?:export )?const ([A-Za-z_$][\w$]*) = /gm)) {
    const name = m[1]
    if (BLOCK_VARS.has(name)) continue
    const start = m.index + m[0].length
    const c = src[start]
    let literal
    if (c === '[' || c === '{') {
      try {
        literal = src.slice(start, matchBracket(src, start) + 1)
      } catch {
        continue
      }
    } else if (c === "'" || c === '"') {
      let i = start + 1
      while (i < src.length && src[i] !== c) i += src[i] === '\\' ? 2 : 1
      literal = src.slice(start, i + 1)
    } else {
      continue
    }
    try {
      const names = Object.keys(consts)
      consts[name] = new Function(...names, `return (${literal})`)(...names.map((n) => consts[n]))
    } catch {
      // references something we didn't resolve — not usable as a const
    }
  }
  return consts
}

export function readBlock(root, name) {
  const { file, anchor } = BLOCKS[name]
  const src = fs.readFileSync(path.join(root, file), 'utf8')
  const consts = fileConsts(src)
  const { start, end } = findBlock(src, anchor)
  const literal = src.slice(start, end)
  const names = Object.keys(consts)
  const value = new Function(...names, `return (${literal})`)(...names.map((n) => consts[n]))
  return { value, consts }
}

// ---- pretty-printer --------------------------------------------------------

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function quote(str) {
  // Repo style: single quotes, double quotes when the string contains one.
  const q = str.includes("'") && !str.includes('"') ? '"' : "'"
  let out = q
  for (const ch of str) {
    if (ch === q || ch === '\\') out += '\\'
    out += ch === '\n' ? '\\n' : ch
  }
  return out + q
}

function printValue(val, indent, constsByValue) {
  const pad = '  '.repeat(indent)
  const padIn = '  '.repeat(indent + 1)
  // A value identical to a same-file const prints as the identifier
  // (HOME_TITLE, LOREM_BODY) so the indirection survives a round trip.
  if (val && typeof val === 'object' || typeof val === 'string') {
    const constName = constsByValue.get(JSON.stringify(val))
    if (constName) return constName
  }
  if (typeof val === 'string') return quote(val)
  if (val === null || typeof val === 'boolean' || typeof val === 'number') return String(val)
  if (Array.isArray(val)) {
    if (val.length === 0) return '[]'
    const inline = val.every((v) => typeof v === 'string') &&
      val.reduce((n, v) => n + v.length + 4, 0) + indent * 2 < 76
    if (inline) return `[${val.map((v) => printValue(v, 0, constsByValue)).join(', ')}]`
    return `[\n${val.map((v) => `${padIn}${printValue(v, indent + 1, constsByValue)},\n`).join('')}${pad}]`
  }
  const keys = Object.keys(val)
  if (keys.length === 0) return '{}'
  let out = '{\n'
  for (const k of keys) {
    const key = IDENT_RE.test(k) ? k : quote(k)
    const v = printValue(val[k], indent + 1, constsByValue)
    // Prettier wraps long scalar strings onto their own line.
    if (typeof val[k] === 'string' && !constsByValue.has(JSON.stringify(val[k])) &&
        padIn.length + key.length + 2 + v.length > 110) {
      out += `${padIn}${key}:\n${padIn}  ${v},\n`
    } else {
      out += `${padIn}${key}: ${v},\n`
    }
  }
  return out + pad + '}'
}

// ---- write -----------------------------------------------------------------

// Regenerates the named block from `value` and returns the new file content
// after verifying the result parses back to exactly the same data. Throws
// (leaving the file untouched) on any mismatch.
export function writeBlock(root, name, value) {
  const { file, anchor } = BLOCKS[name]
  const abs = path.join(root, file)
  const src = fs.readFileSync(abs, 'utf8')
  const consts = fileConsts(src)
  const constsByValue = new Map(Object.entries(consts).map(([k, v]) => [JSON.stringify(v), k]))
  const { start, end } = findBlock(src, anchor)
  const indent = src.lastIndexOf('\n', start) === -1
    ? 0
    : Math.floor((start - src.lastIndexOf('\n', start) - 1 - anchor.length) / 2)
  const literal = printValue(value, indent, constsByValue)
  const next = src.slice(0, start) + literal + src.slice(end)

  const check = findBlock(next, anchor)
  const names = Object.keys(consts)
  const reparsed = new Function(...names, `return (${next.slice(check.start, check.end)})`)(
    ...names.map((n) => consts[n]))
  const a = JSON.stringify(reparsed)
  const b = JSON.stringify(value)
  if (a !== b) throw new Error(`round-trip mismatch writing ${name} — file left untouched`)

  fs.writeFileSync(abs, next)
  return next
}
