import { useEffect, useRef, useState } from 'react'

/**
 * `<ConceptArtGallery gameSlug="..." />` — categorized, horizontally
 * scrollable concept-art rows for a game.
 *
 * Hands-off authoring model: a designer drops a source image into
 * `src/assets/games/<slug>/concept/<category>/<filename>` and commits.
 *
 * Two tracks, by file format:
 *   - **jpg / jpeg / png** go through `scripts/generate-image-variants.mjs`,
 *     which produces WebP variants at 500/800/1080/1600w alongside the source
 *     (or one native-width variant if the source is narrower than all of
 *     those). Only the variants are shipped; the original never is.
 *   - **svg / gif** are served as-is, with no variants and no srcSet —
 *     resampling vector art degrades it, and flattening an animated GIF to a
 *     still frame loses the animation.
 *
 * How it works:
 *   - `import.meta.glob` (eager, URL mode) enumerates every variant and every
 *     passthrough source under `src/assets/games/*\/concept\/*\/`. The raster
 *     originals are deliberately not globbed — see the note on the globs below.
 *   - Both tracks are grouped by gameSlug → category → stem; each row renders
 *     one `<img>` per stem. Variant-backed tiles get a srcSet across that
 *     stem's widths, with the widest variant as the `src` fallback.
 *   - Files within a category are sorted alphabetically by filename.
 *     Use `01-`, `02-`, ... prefixes if you want manual ordering.
 *   - Category subfolder names become row labels (uppercase). Rows are
 *     ordered alphabetically by folder name.
 *   - Alt text is derived from the filename (dashes → spaces, sentence
 *     case). Override by renaming the file.
 *   - Chevron buttons appear at the left and right edges of each strip
 *     when there's more content in that direction; clicking scrolls.
 *
 * Renders nothing if the slug has no variants and no passthrough sources.
 * Variants are gitignored and regenerated by the build, so this is a
 * generated-file dependency: see the `generate-image-variants` plugin in
 * `vite.config.js`.
 */

// Eagerly enumerate every generated variant up front. Vite resolves these to
// hashed URLs at build time and tree-shakes nothing — the gallery's "drop a
// file in" promise needs *all* files known statically.
//
// Only variants are globbed, never the source jpg/png. Globbing a source with
// `?url` makes Vite copy that multi-megabyte original into `docs/` even though
// no browser ever fetches it (with `w` descriptors the `src` fallback is not a
// candidate). Deriving everything from variant filenames keeps ~68 MB of
// originals out of every build and deploy.
const variantModules = import.meta.glob('/src/assets/games/*/concept/*/*-[0-9]*w.webp', { eager: true, query: '?url', import: 'default' })

// Formats the variant pipeline can't improve on are served as-is, no srcSet.
// SVG is vector — resampling it to fixed pixel widths would be a downgrade.
// GIF is usually animated, and sharp would flatten it to a single still frame.
// Emitting these originals is fine: the multi-megabyte files the glob above
// exists to avoid are all jpg/png.
const passthroughModules = import.meta.glob('/src/assets/games/*/concept/*/*.{svg,gif}', { eager: true, query: '?url', import: 'default' })

// Build an index: slug → category → [{ filename, src, srcSet, alt }, ...]
const galleryIndex = buildGalleryIndex(variantModules, passthroughModules)

function buildGalleryIndex(variants, passthrough) {
  // Group variants by their source image: slug → category → stem → [{ width, url }]
  const bySlug = new Map()
  for (const [path, url] of Object.entries(variants)) {
    const match = path.match(/\/src\/assets\/games\/([^/]+)\/concept\/([^/]+)\/(.+)-(\d+)w\.webp$/)
    if (!match) continue
    const [, slug, category, stem, width] = match

    if (!bySlug.has(slug)) bySlug.set(slug, new Map())
    const categories = bySlug.get(slug)
    if (!categories.has(category)) categories.set(category, new Map())
    const stems = categories.get(category)
    if (!stems.has(stem)) stems.set(stem, [])
    stems.get(stem).push({ width: Number(width), url })
  }

  // Collapse each stem's variant list into one renderable item. The widest
  // variant doubles as the `src` fallback for browsers without srcSet support.
  const index = new Map()
  for (const [slug, categories] of bySlug) {
    const outCategories = new Map()
    for (const [category, stems] of categories) {
      const items = []
      for (const [stem, list] of stems) {
        list.sort((a, b) => a.width - b.width)
        items.push({
          filename: stem,
          src: list[list.length - 1].url,
          srcSet: list.map((v) => `${v.url} ${v.width}w`).join(', '),
          alt: filenameToAlt(stem),
        })
      }
      outCategories.set(category, items)
    }
    index.set(slug, outCategories)
  }

  // Merge in the passthrough sources, which render straight from the file.
  for (const [path, url] of Object.entries(passthrough)) {
    const match = path.match(/\/src\/assets\/games\/([^/]+)\/concept\/([^/]+)\/(.+)\.(svg|gif)$/i)
    if (!match) continue
    const [, slug, category, stem] = match

    if (!index.has(slug)) index.set(slug, new Map())
    const categories = index.get(slug)
    if (!categories.has(category)) categories.set(category, [])
    const items = categories.get(category)
    // A raster source of the same name already produced variants — keep those
    // and skip this one, rather than render two tiles under a duplicate key.
    if (items.some((item) => item.filename === stem)) continue
    items.push({ filename: stem, src: url, srcSet: undefined, alt: filenameToAlt(stem) })
  }

  // Sort each category's files alphabetically.
  for (const categories of index.values()) {
    for (const items of categories.values()) {
      items.sort((a, b) => a.filename.localeCompare(b.filename, undefined, { numeric: true }))
    }
  }
  return index
}

function filenameToAlt(stem) {
  const cleaned = stem.replace(/[-_]+/g, ' ').trim()
  if (!cleaned) return ''
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
}

function categoryLabel(category) {
  return category.replace(/[-_]+/g, ' ').toUpperCase()
}

/**
 * One category row. Owns its scroll strip + chevron button.
 */
function ConceptArtRow({ category, items }) {
  const stripRef = useRef(null)
  const [showPrev, setShowPrev] = useState(false)
  const [showNext, setShowNext] = useState(false)
  const label = categoryLabel(category)

  useEffect(() => {
    const strip = stripRef.current
    if (!strip) return undefined
    const update = () => {
      const overflows = strip.scrollWidth > strip.clientWidth + 1
      const atStart = strip.scrollLeft <= 1
      const atEnd = strip.scrollLeft + strip.clientWidth >= strip.scrollWidth - 1
      setShowPrev(overflows && !atStart)
      setShowNext(overflows && !atEnd)
    }
    update()
    strip.addEventListener('scroll', update, { passive: true })
    const ro = new ResizeObserver(update)
    ro.observe(strip)
    // Images load asynchronously and change scrollWidth — re-check on each load.
    const imgs = strip.querySelectorAll('img')
    imgs.forEach((img) => img.addEventListener('load', update))
    return () => {
      strip.removeEventListener('scroll', update)
      ro.disconnect()
      imgs.forEach((img) => img.removeEventListener('load', update))
    }
  }, [items])

  const scrollBy = (direction) => {
    const strip = stripRef.current
    if (!strip) return
    const delta = Math.round(strip.clientWidth * 0.8) * direction
    strip.scrollBy({ left: delta, behavior: 'smooth' })
  }

  return (
    <div className="concept-art-row">
      <div className="concept-art-row-label-wrapper">
        <span className="concept-art-row-label">{label}</span>
        <span className="concept-art-row-divider" aria-hidden="true" />
      </div>
      <div ref={stripRef} className="concept-art-strip">
        {items.map((item) => (
          <figure key={item.filename} className="concept-art-tile">
            <img
              src={item.src}
              srcSet={item.srcSet}
              sizes="(max-width: 767px) 70vw, (max-width: 1199px) 40vw, 28vw"
              loading="lazy"
              alt={item.alt}
              className="concept-art-image"
            />
          </figure>
        ))}
      </div>
      <button
        type="button"
        className="concept-art-strip-prev"
        onClick={() => scrollBy(-1)}
        hidden={!showPrev}
        aria-label={`Scroll ${label.toLowerCase()} concept art backward`}
      >
        <svg viewBox="0 0 18 18" aria-hidden="true">
          <path d="M12 3l-6 6 6 6" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>
      <button
        type="button"
        className="concept-art-strip-next"
        onClick={() => scrollBy(1)}
        hidden={!showNext}
        aria-label={`Scroll ${label.toLowerCase()} concept art forward`}
      >
        <svg viewBox="0 0 18 18" aria-hidden="true">
          <path d="M6 3l6 6-6 6" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>
    </div>
  )
}

export default function ConceptArtGallery({ gameSlug }) {
  const categories = galleryIndex.get(gameSlug)
  if (!categories || categories.size === 0) return null

  const orderedCategories = [...categories.keys()].sort()

  return (
    <section className="concept-art-section">
      <div className="concept-art-heading-wrapper">
        <h3 className="concept-art-heading">Concept Art</h3>
      </div>
      {orderedCategories.map((category) => {
        const items = categories.get(category)
        if (!items || items.length === 0) return null
        return <ConceptArtRow key={category} category={category} items={items} />
      })}
    </section>
  )
}
